name = "T4ATCIAlgorithms"
uuid = "afea4b4e-08e0-4d7c-9da1-dbc7777ac29f"
version = "0.5.0"
authors = ["Hiroshi Shinaoka <h.shinaoka@gmail.com> and contributors"]

[deps]
Distributed = "8ba89e20-285c-5b6f-9357-94700520ee1b"
EllipsisNotation = "da5c29d0-fa7d-589e-88eb-ea29b0a81949"
ITensors = "9136182c-28ba-11e9-034c-db9fb085ebd5"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
OrderedCollections = "bac558e1-5e72-5ebc-8fee-abe8a469f55d"
T4AQuantics = "99202d80-6772-4c79-995b-f2660cf2bd6d"
T4ATensorCI = "14428447-6903-48c7-83df-f2cb08af9918"
TensorCrossInterpolation = "b261b2ec-6378-4871-b32e-9173bb050604"

[compat]
EllipsisNotation = "1"
OrderedCollections = "1"
T4AQuantics = "0.5"
T4ATensorCI = "0.10"
TensorCrossInterpolation = "0.9"
julia = "1.10"

[extras]
Aqua = "4c88cf16-eb10-579e-8560-4a9242c79595"
HubbardAtoms = "4f3da25b-ea28-4d4f-a81f-380d3f5e56a6"
JET = "c3a54625-cd67-489e-a8e7-0a5a0ff4e31b"
QuanticsGrids = "634c7f73-3e90-4749-a1bd-001b8efc642d"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
SparseIR = "4fe2279e-80f0-4adb-8463-ee114ff56b7d"
T4AITensorCompat = "864b39ca-388c-4f43-a593-a1076cf4b253"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Aqua", "JET", "Test", "Random", "QuanticsGrids", "SparseIR", "HubbardAtoms", "T4AITensorCompat"]
